# Travis manifest for Django proyect 

language: python

sudo: required

python:
  - 3.6

services: postgresql


before_install:
  - export DJANGO_SETTINGS_MODULE=superlists.settings  
  - export PIP_USE_MIRRORS=true
  - export TRAVIS=true

  - export TRAVIS_DATABASE_NAME=travisci
  - export TRAVIS_DATABASE_USER=postgres

install:
  - ./install_requirements.sh

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres
- ./migrate_db.sh

script:
  - ./run_unit_tests.sh


notifications:
  email:
    recipients:
      - josmilope@gmail.com
    on_success: always
    on_failure: always