# Travis manifest for Django proyect 

language: python

python:
  - 3.6

before_install:
  - export DJANGO_SETTINGS_MODULE=superlists.superlists.settings  
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - ./run_unit_tests.sh

  
